Repository wecode-bootcamp-korea/33-2nd-wantUS-frontend, pull requests merged in 2022-06, with the labels that each got.

#6 [33기 안성주] Add : Nav 기능 및 레이아웃 구현 완료 (리뷰반영완료)
  package-lock.json
  package.json
  src/Router.js
  src/components/nav/DropMenu.js
  src/components/nav/Nav.js
  src/pages/mypage/Mypage.js
Labels: 완료

#1 [33기 염종은] ADD: jobDetail page layout
  .vscode/settings.json
  package-lock.json
  package.json
  public/data/followData.json
  public/data/jobDetailData.json
  src/Router.js
  src/pages/jobdetail/Apply.js
  src/pages/jobdetail/ApplyInformation.js
  src/pages/jobdetail/CompanySlide.js
  src/pages/jobdetail/DetailMap.js
  src/pages/jobdetail/JobDetail.js
  src/pages/jobdetail/JobDetailDescription.js
  src/pages/jobdetail/NaverMaps.js
  src/pages/jobdetail/NextArrow.js
  src/pages/jobdetail/PrevArrow.js
  src/pages/jobdetail/SubmitModal.js
  src/pages/likePage/LikePage.js
Labels: 완료

#11 [33기 염종은]ADD: footer layout
  src/Router.js
  src/components/footer/Footer.js
Labels: 완료

#4 [33기 안성주] Modify : Resume 기능 및 레이아웃 구현 완료 (리뷰반영)
  package-lock.json
  public/data/readme.md
  public/data/resumeuserdata.json
  src/Router.js
  src/pages/mypage/Mypage.js
  src/pages/resume/Resume.js
  src/pages/resume/ResumeItemList.js
  src/styles/GlobalStyle.js
Labels: Conflict 해결 요청

#7 [33기 안성주] Add : mypage 리뷰 반영 중 도움 요청
  public/data/userapplydata.json
  public/data/userprofiledata.json
  src/pages/mypage/Mypage.js
  src/pages/mypage/MypageAside.js
  src/pages/mypage/ProfileApplyCompany.js
  src/pages/mypage/ProfileApplyStatus.js
  src/pages/mypage/UserApplyList.js
Labels: 완료

#2 [33기 김현주]Add: jobList 페이지 기본 기능 구현
  public/images/jobList/loading.gif
  public/workers/worker.js
  src/Router.js
  src/components/nav/components/Search.js
  src/components/nav/components/SearchModal.js
  src/hooks/useFetch.js
  src/pages/joblist/JobList.js
  src/pages/joblist/components/JobItem.js
  src/pages/joblist/components/JobItemList.js
  src/pages/joblist/components/MainFilter.js
  src/pages/joblist/components/Navbar.js
  src/pages/joblist/components/SkeletonUI.js
  src/pages/joblist/components/SubFilter.js
Labels: Conflict 해결 요청, 멘토 리뷰 요청

#10 [33기 김정준] 메인페이지 레이아웃
  package-lock.json
  package.json
  public/data/MainData.json
  public/data/MainImg.json
  public/images/company1.jpg
  public/images/company2.jpg
  public/images/company3.jpg
  public/images/company4.jpg
  public/images/company5.jpg
  public/images/company6.jpg
  public/images/company7.jpg
  public/images/company8.jpg
  src/Router.js
  src/pages/main/ApplyNowCarousel.js
  src/pages/main/HeaderCarousel.js
  src/pages/main/Main.js
  src/pages/main/MidNavBar.js
  src/pages/main/SuggestCarousel.js
Labels: Conflict 해결 요청, 멘토 리뷰 요청
